### ISSUE TITLE
How can I make this curl command work with php

### ISSUE THREAD

**Issue by marrobHD** [incarnate/curl-to-php#17]
curl -X POST -H "Authorization: Bearer ABCDE" \-H "Content-Type: application/json" \-d '{"entity_id": "script.server_boot_test"}' \https://XXX.duckdns.org:8123/api/services/script/turn_on

Thanks for help

**Comment by incarnate** [comment]
Hi @marrobHD 
This command converts without any issues I can see using https://incarnate.github.io/curl-to-php/

As this issue is already old I close now, please respond if there is a problem with the generated PHP code.
