### ISSUE TITLE
Problem with post audio and certificate file

### ISSUE THREAD

**Issue by kvu-luong** [incarnate/curl-to-php#21]
I got an issue with sending audio file and certificate file to get data from server, I have tried with the code like below
```<?php

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'my_api_url');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
//setting file
curl_setopt($ch, CURLOPT_POSTFIELDS, array('file'=>'@'.realpath('audio/sound.wav')));

$headers = array();
$token = 'mytoken';
$headers[] = 'token:'.$token;

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CAINFO ,dirname(__FILE__).'\certification.crt');
curl_setopt($ch, CURLOPT_CAPATH,dirname(__FILE__).'\certification.crt');
// curl_setopt($ch, CURLOPT_TIMEOUT, 10); 
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;
```
The CURL format for the code above like below
```curl  --request POST --cacert $CERT_FILE  -H "token: $YOUR_TOKEN"  -F "file=@$PATH_TO_FILE"  my_api_url```
But it doesn't working,  Are there any suggestion to solve this issue. Thank you in advance for any sugguestion.

**Comment by thinker-gao** [comment]
you can   set curl with no ssl  verify ,for  example:
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0)

**Comment by kvu-luong** [comment]
Thank you for your response.

Vào Th 7, 21 thg 9, 2019 vào lúc 14:28 高久峰 <notifications@github.com> đã
viết:
