### ISSUE TITLE
--data-binary not work correctly

### ISSUE THREAD

**Issue by artispretis** [incarnate/curl-to-php#3]
`curl -H "server-method: SendNew" -H "client-ver: 105" --data-binary '{"a":[],"y":null,"km":22}' --compressed http://localhost/post.php`

curl-to-php generate 
`curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");`

need to
`
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, '{"a":[],"y":null,"km":22}');
`

**Comment by incarnate** [comment]
I've added in basic support for `--data-binary`, thanks for the suggestion!
