### ISSUE TITLE
Post Parameters

### ISSUE THREAD

**Issue by vinfur** [incarnate/curl-to-php#38]
When There are Post parameters Still Request Type is set to get
Also Post parameters are totally not available in request

**Comment by NabiKAZ** [comment]
Would do you provide sample curl command?

**Comment by mikualpha** [comment]
There is a curl command what copied from Chrome(90.0) "Copy as curl(bash)" in F12.
Replaced domain and cookies:
`curl 'https://sample.com/test.php?' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: max-age=0' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Origin: https://sample.com' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'DNT: 1' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-Fetch-Dest: iframe' \
  -H 'Referer: https://sample.com/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'Cookie: there_is_a_cookie' \
  --data-raw '__lib=test&__type=test' \
  --compressed`

**Comment by NabiKAZ** [comment]
Here `--data-raw` was used.
There is PR https://github.com/incarnate/curl-to-php/pull/35 and waiting for marge.

**Comment by incarnate** [comment]
#35 merged, thanks for submitting the issue.
