### ISSUE TITLE
Problem with post curl field and quotes

### ISSUE THREAD

**Issue by pifagor87** [incarnate/curl-to-php#7]
If, we have console curl:
-d type_name=xxx -d attributes='{"name":"test"}'
we get convert value
curl_setopt($ch, CURLOPT_POSTFIELDS, "type_name=xxx&attributes='{"name":"test"}'");
It is bug. Right convert:
curl_setopt($ch, CURLOPT_POSTFIELDS, "type_name=xxx&attributes={"name":"test"}");

I solved the issue here:
https://github.com/incarnate/curl-to-php/pull/6

**Comment by straube** [comment]
@pifagor87 It seems like the project is not active anymore. 😞

**Comment by incarnate** [comment]
Sorry for not getting to this sooner, I've merged #6 - thanks @pifagor87 !
